# Generated for InfoEdu LMS initial schema.
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Talaba'), ('teacher', 'O‘qituvchi'), ('admin', 'Administrator')], default='student', max_length=16)),
                ('student_id', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('faculty', models.CharField(blank=True, max_length=255)),
                ('group_name', models.CharField(blank=True, max_length=64)),
                ('avatar_url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('department', models.CharField(blank=True, max_length=160)),
                ('study_streak_days', models.PositiveIntegerField(default=0)),
                ('longest_streak_days', models.PositiveIntegerField(default=0)),
                ('total_study_minutes', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={'abstract': False},
            managers=[('objects', django.contrib.auth.models.UserManager())],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('cover_image', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('level', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('estimated_study_hours', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin']}, on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to='lms.user')),
            ],
            options={'ordering': ['code']},
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Boshlanmagan'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallangan')], default='not_started', max_length=16)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms.user')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='lms.course')),
            ],
            options={'ordering': ['course_id', 'order']},
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('lesson_type', models.CharField(choices=[('theory', 'Nazariya'), ('presentation', 'Taqdimot'), ('video', 'Video'), ('test', 'Test')], max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.module')),
            ],
            options={'ordering': ['module_id', 'order']},
        ),
        migrations.CreateModel(
            name='TheoryContent',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('reading_time_minutes', models.PositiveIntegerField(default=5)),
                ('summary', models.TextField(blank=True)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theory_content', to='lms.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('pptx', 'PPTX')], default='pdf', max_length=8)),
                ('file_size', models.CharField(blank=True, max_length=32)),
                ('file_url', models.URLField(blank=True)),
                ('embed_url', models.URLField(blank=True)),
                ('slides', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_content', to='lms.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('embed_type', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('direct', 'Direct')], default='youtube', max_length=16)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('transcript', models.TextField(blank=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_content', to='lms.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('time_limit_minutes', models.PositiveIntegerField(default=20)),
                ('attempts_allowed', models.PositiveIntegerField(default=3)),
                ('passing_score_percent', models.PositiveIntegerField(default=60)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_content', to='lms.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('true_false', 'True/False'), ('short_text', 'Short text')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField()),
                ('explanation', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('code_snippet', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('topic', models.CharField(default='Umumiy', max_length=120)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.test')),
            ],
            options={'ordering': ['test_id', 'order']},
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('last_position_seconds', models.PositiveIntegerField(default=0)),
                ('watched_percentage', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lms.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='lms.user')),
            ],
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('answer_reviews', models.JSONField(blank=True, default=list)),
                ('topic_breakdowns', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='lms.user')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms.test')),
            ],
            options={'ordering': ['-submitted_at']},
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lms.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.question')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('lesson', 'Lesson'), ('test', 'Test'), ('result', 'Result'), ('announcement', 'Announcement'), ('system', 'System')], default='system', max_length=16)),
                ('link_target', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='lms.user')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(model_name='enrollment', constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_enrollment')),
        migrations.AddConstraint(model_name='module', constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_module_order')),
        migrations.AddConstraint(model_name='lesson', constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_lesson_order')),
        migrations.AddConstraint(model_name='question', constraint=models.UniqueConstraint(fields=('test', 'order'), name='unique_question_order')),
        migrations.AddConstraint(model_name='lessonprogress', constraint=models.UniqueConstraint(fields=('student', 'lesson'), name='unique_lesson_progress')),
        migrations.AddConstraint(model_name='testattempt', constraint=models.UniqueConstraint(fields=('student', 'test', 'attempt_number'), name='unique_test_attempt_number')),
        migrations.AddConstraint(model_name='testanswer', constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_answer')),
    ]
